/**
 * Question-answer mapping from Excel file
 * This file will be automatically generated by the update-qa-from-excel.js script
 */

export type QuestionAnswerPair = {
  question: string;
  answer: string;
};

// Initial empty mapping - will be populated by the script
export const questionAnswerMap: Record<string, QuestionAnswerPair> = {};

/**
 * Gets a question-answer pair for a given file path
 * @param filePath The file path without extension
 * @returns Question-answer pair or empty strings if not found
 */
export function getQuestionAnswer(filePath: string): QuestionAnswerPair {
  // Clean the file path - remove extension if present
  const cleanPath = filePath.replace(/\.[^/.]+$/, '');
  
  // Try to find an exact match
  if (questionAnswerMap[cleanPath]) {
    return questionAnswerMap[cleanPath];
  }
  
  // If no exact match, try to find a match based on the filename only
  const fileName = cleanPath.split('/').pop() || '';
  
  for (const key in questionAnswerMap) {
    if (key.endsWith(fileName)) {
      return questionAnswerMap[key];
    }
  }
  
  // Return empty strings if no match found
  return { question: '', answer: '' };
}