export const hardcodedBook1Resources: Record<string, TeacherResource[]> = {
  "book1-unit1": [
    { type: "video", embedUrl: "https://www.youtube.com/embed/7CuZr1Dz3sk" },
    { type: "video", embedUrl: "https://www.youtube.com/embed/7CuZr1Dz3sk" },
    { type: "video", embedUrl: "https://www.youtube.com/embed/gVIFEVLzP4o" },
    { type: "game", embedUrl: "https://wordwall.net/embed/7a5f9c9d02764745b1b471a56483ddf2" },
    { type: "game", embedUrl: "https://wordwall.net/embed/aa9083a0802940d7abd8dfbb0ea2113d" },
  ],
  "book1-unit2": [
    { type: "video", embedUrl: "https://www.youtube.com/embed/41cJ0mqWses" },
    { type: "video", embedUrl: "https://www.youtube.com/embed/Ix4dSjKqwvc" },
    { type: "video", embedUrl: "https://www.youtube.com/embed/Ct6BUPvE2sM" },
    { type: "video", embedUrl: "https://www.youtube.com/embed/t24dt39WNG0" },
    { type: "video", embedUrl: "https://www.youtube.com/embed/F9OdB53UGmA" },
    { type: "video", embedUrl: "https://www.youtube.com/embed/JLMsm-D7kjk" },
    { type: "game", embedUrl: "https://wordwall.net/embed/db3feb02d90048c794504e2a408ef901" },
  ],
  "book1-unit3": [
    { type: "video", embedUrl: "https://www.youtube.com/embed/WsiRSWthV1k" },
    { type: "video", embedUrl: "https://www.youtube.com/embed/DiXMZJi_2NU" },
    { type: "video", embedUrl: "https://www.youtube.com/embed/E_VcSQn73do" },
    { type: "video", embedUrl: "https://www.youtube.com/embed/RNUZBHlRH4Y" },
    { type: "video", embedUrl: "https://www.youtube.com/embed/SFE0mMWbA-Y" },
    { type: "game", embedUrl: "https://wordwall.net/embed/94341df31881431a8e6bb5e707557a42" },
    { type: "game", embedUrl: "https://wordwall.net/embed/c95d7edfe0e64b77be765f3289a7c3e3" },
  ],
  "book1-unit4": [
    { type: "video", embedUrl: "https://www.youtube.com/embed/5su1M6NdG-I" },
    { type: "video", embedUrl: "https://www.youtube.com/embed/iztRyiYIwUs" },
    { type: "video", embedUrl: "https://www.youtube.com/embed/ykTR0uFGwE0" },
    { type: "video", embedUrl: "https://www.youtube.com/embed/teMU8dHLqSI" },
    { type: "video", embedUrl: "https://www.youtube.com/embed/kR6Qcqx2fJE" },
    { type: "game", embedUrl: "https://wordwall.net/embed/cc9df848c6a94c99b8dcf9c9b65caeb4" },
    { type: "game", embedUrl: "https://wordwall.net/embed/61576e9315e949fd9a89477f5807ce46" },
  ],
  "book1-unit5": [
    { type: "video", embedUrl: "https://www.youtube.com/embed/1EyrquyRg5s" },
    { type: "video", embedUrl: "https://www.youtube.com/embed/VvrG4JguNQk" },
    { type: "video", embedUrl: "https://www.youtube.com/embed/XqZsoesa55w" },
    { type: "video", embedUrl: "https://www.youtube.com/embed/GR2o6k8aPlI" },
    { type: "video", embedUrl: "https://www.youtube.com/embed/d_WQEw13TCo" },
    { type: "game", embedUrl: "https://wordwall.net/embed/e5f62afa86814cc98336327469ce1554" },
    { type: "game", embedUrl: "https://wordwall.net/embed/d1bc1e8629a445468a696f03f372e5e9" },
    { type: "game", embedUrl: "https://wordwall.net/embed/1c606c6af00643d692fc0199a60c2b2c" },
  ],
  "book1-unit6": [
    { type: "video", embedUrl: "https://www.youtube.com/embed/jYAWf8Y91hA" },
    { type: "video", embedUrl: "https://www.youtube.com/embed/Asb8N0nz9OI" },
    { type: "video", embedUrl: "https://www.youtube.com/embed/NUquLTPhMwg" },
    { type: "video", embedUrl: "https://www.youtube.com/embed/zxIpA5nF_LY" },
    { type: "video", embedUrl: "https://www.youtube.com/embed/0LNuoKsAtN8" },
    { type: "game", embedUrl: "https://wordwall.net/embed/54d466d5a13948c6acbafc5729e6d887" },
    { type: "game", embedUrl: "https://wordwall.net/embed/360776cf889d4170872d084aa81d3995" },
  ],
  "book1-unit7": [
    { type: "video", embedUrl: "https://www.youtube.com/embed/nsDanlM8_3c" },
    { type: "video", embedUrl: "https://www.youtube.com/embed/HG361wJyDY0" },
    { type: "video", embedUrl: "https://www.youtube.com/embed/JooOjnzWv3E" },
    { type: "game", embedUrl: "https://wordwall.net/embed/43666156c96d455686dc6620f025c979" },
    { type: "game", embedUrl: "https://wordwall.net/embed/6b732e25ee5641e38bdb2785e4fe390b" },
    { type: "game", embedUrl: "https://wordwall.net/embed/a0ac3f124ba146bda184a6fe30e24d5b" },
  ],
  "book1-unit8": [
    { type: "video", embedUrl: "https://www.youtube.com/embed/TJhfl5vdxp4" },
    { type: "video", embedUrl: "https://www.youtube.com/embed/03pyY9C2Pm8" },
    { type: "video", embedUrl: "https://www.youtube.com/embed/0B6Ge0FzHG0" },
    { type: "video", embedUrl: "https://www.youtube.com/embed/FOZLDVnvrZM" },
    { type: "video", embedUrl: "https://www.youtube.com/embed/lcl8uB2AWM0" },
    { type: "video", embedUrl: "https://www.youtube.com/embed/9GFEjNL0XXw" },
    { type: "game", embedUrl: "https://wordwall.net/embed/a3dfd9e2aa764904a073828747936488" },
  ],
  "book1-unit9": [
    { type: "video", embedUrl: "https://www.youtube.com/embed/N6C8QueZdIc" },
    { type: "video", embedUrl: "https://www.youtube.com/embed/YxARpdWQGpo" },
    { type: "video", embedUrl: "https://www.youtube.com/embed/B2pmcJPQW3Q" },
    { type: "video", embedUrl: "https://www.youtube.com/embed/_QvqsubsAPI" },
    { type: "game", embedUrl: "https://wordwall.net/embed/4232fb7566f54ac486525e731f02f4ac" },
    { type: "game", embedUrl: "https://wordwall.net/embed/7ab75a0b89ac40718d8978cf71ef910b" },
  ],
  "book1-unit10": [
    { type: "video", embedUrl: "https://www.youtube.com/embed/z2ucP1_EmO0" },
    { type: "video", embedUrl: "https://www.youtube.com/embed/gEQOtbi7SbI" },
    { type: "game", embedUrl: "https://wordwall.net/embed/0cafad4a8bd34df08bc5c773341708c3" },
    { type: "game", embedUrl: "https://wordwall.net/embed/86601794244d4f05896b54f10ea16442" },
    { type: "game", embedUrl: "https://wordwall.net/embed/16380f32f8d4405baf763ba85cd19368" },
  ],
  "book1-unit11": [
    { type: "video", embedUrl: "https://www.youtube.com/embed/EHnO_LpfsIg" },
    { type: "video", embedUrl: "https://www.youtube.com/embed/7OUYAQttqdg" },
    { type: "video", embedUrl: "https://www.youtube.com/embed/hexM3GaE2J4" },
    { type: "video", embedUrl: "https://www.youtube.com/embed/sXcs_4ez8-M" },
    { type: "video", embedUrl: "https://www.youtube.com/embed/VS9qBeInJ0U" },
    { type: "video", embedUrl: "https://www.youtube.com/embed/NavWWM2iTEw" },
    { type: "video", embedUrl: "https://www.youtube.com/embed/Wrjqz2GTzzI" },
    { type: "video", embedUrl: "https://www.youtube.com/embed/TBLFMXU8FLI" },
    { type: "video", embedUrl: "https://www.youtube.com/embed/MtA9Ni-wxUI" },
    { type: "game", embedUrl: "https://wordwall.net/embed/7b81d9ee5f4f450fa1f807d3c0caf204" },
    { type: "game", embedUrl: "https://wordwall.net/embed/c9bf24cc7b5a4ec888974e540da1a160" },
  ],
  "book1-unit12": [
    { type: "video", embedUrl: "https://www.youtube.com/embed/168xwPpHF-s" },
    { type: "video", embedUrl: "https://www.youtube.com/embed/mV-TnrvUJ9Q" },
    { type: "video", embedUrl: "https://www.youtube.com/embed/kIg__488rCs" },
    { type: "video", embedUrl: "https://www.youtube.com/embed/pWepfJ-8XU0" },
    { type: "video", embedUrl: "https://www.youtube.com/embed/RAObh4cLDAI" },
    { type: "video", embedUrl: "https://www.youtube.com/embed/6BK49n2UWA0" },
    { type: "video", embedUrl: "https://www.youtube.com/embed/BT39vDpfI5s" },
    { type: "video", embedUrl: "https://www.youtube.com/embed/AkZrk8KL76c" },
    { type: "video", embedUrl: "https://www.youtube.com/embed/hmVYCS_hJk0" },
    { type: "video", embedUrl: "https://www.youtube.com/embed/DHb4-CCif7U" },
    { type: "video", embedUrl: "https://www.youtube.com/embed/xERTESWbqhU" },
    { type: "video", embedUrl: "https://www.youtube.com/embed/ftLIV92ovgk" },
    { type: "video", embedUrl: "https://www.youtube.com/embed/mfReSbQ7jzE" },
    { type: "video", embedUrl: "https://www.youtube.com/embed/q780dw-1QE8" },
    { type: "video", embedUrl: "https://www.youtube.com/embed/oBF-_ZMkuH8" },
    { type: "video", embedUrl: "https://www.youtube.com/embed/QQZ03_v3K6Y" },
    { type: "video", embedUrl: "https://www.youtube.com/embed/mVE9pYdwX-I" },
    { type: "video", embedUrl: "https://www.youtube.com/embed/wTTz2dL0jb8" },
    { type: "video", embedUrl: "https://www.youtube.com/embed/RE5tvaveVak" },
    { type: "video", embedUrl: "https://www.youtube.com/embed/cd8HE9HCl-c" },
    { type: "video", embedUrl: "https://www.youtube.com/embed/g2GjP8Heqjw" },
    { type: "video", embedUrl: "https://www.youtube.com/embed/pdIZH2Zk_G0" },
    { type: "video", embedUrl: "https://www.youtube.com/embed/98dEG7WjF1M" },
    { type: "video", embedUrl: "https://www.youtube.com/embed/O2NwvUB41rA" },
    { type: "video", embedUrl: "https://www.youtube.com/embed/I8GeA3anPdo" },
    { type: "video", embedUrl: "https://www.youtube.com/embed/gpBuaU5OPi8" },
    { type: "video", embedUrl: "https://www.youtube.com/embed/pd5kLz3jc4o" },
    { type: "video", embedUrl: "https://www.youtube.com/embed/c3v0rJqyCTM" },
    { type: "video", embedUrl: "https://www.youtube.com/embed/KAYZo8a8AHg" },
    { type: "video", embedUrl: "https://www.youtube.com/embed/LFrKYjrIDs8" },
    { type: "video", embedUrl: "https://www.youtube.com/embed/PfyJQEIsMt0" },
    { type: "video", embedUrl: "https://www.youtube.com/embed/_Ir0Mc6Qilo" },
    { type: "video", embedUrl: "https://www.youtube.com/embed/opyc2bvtBpo" },
    { type: "video", embedUrl: "https://www.youtube.com/embed/qI7nYvVXudo" },
    { type: "video", embedUrl: "https://www.youtube.com/embed/hA3ClzoslBo" },
    { type: "video", embedUrl: "https://www.youtube.com/embed/radrRGGe-J0" },
    { type: "video", embedUrl: "https://www.youtube.com/embed/hft6uJQIF4g" },
    { type: "video", embedUrl: "https://www.youtube.com/embed/e6J63bCyuwU" },
    { type: "game", embedUrl: "https://wordwall.net/embed/64037ab981484c46a7fdd820ecbe0ca1" },
    { type: "game", embedUrl: "https://wordwall.net/embed/f80c09de5f2a431ba2eadc93b12cac3c" },
    { type: "game", embedUrl: "https://wordwall.net/embed/a2e9207ad2234b8d8ab2daf8c9e439c5" },
    { type: "game", embedUrl: "https://wordwall.net/embed/62517d93002d490d8ede52bb5c748ebc" },
    { type: "game", embedUrl: "https://wordwall.net/embed/55c7caefb2fe48feb7798940327e0197" },
    { type: "game", embedUrl: "https://wordwall.net/embed/ef14eb2bd2254ff8b01d8e376ff7165e" },
    { type: "game", embedUrl: "https://wordwall.net/embed/e297e5091ade4d4fab9a92c15491343e" },
    { type: "game", embedUrl: "https://wordwall.net/embed/886c609003c149f1b21d1a89d83700c4" },
    { type: "game", embedUrl: "https://wordwall.net/embed/bcf4964f6d694547a72d3909fd32d86c" },
    { type: "game", embedUrl: "https://wordwall.net/embed/96231f6b6a204fb887b683064b6ac962" },
    { type: "game", embedUrl: "https://wordwall.net/embed/4dd9de248dbb4b1e930c461ee3f5a6a5" },
    { type: "game", embedUrl: "https://wordwall.net/embed/295589dd42e442228956c9fa7365aa96" },
    { type: "game", embedUrl: "https://wordwall.net/embed/0d86e97d1d264023b65d07f200681c1b" },
    { type: "game", embedUrl: "https://wordwall.net/embed/17f93ebd3a064bdbb6091669ff5f7318" },
    { type: "game", embedUrl: "https://wordwall.net/embed/89a170a27647484d8c98c94a5f04f9e7" },
    { type: "game", embedUrl: "https://wordwall.net/embed/e4a93912a9784dc6b9171a1c54272864" },
    { type: "game", embedUrl: "https://wordwall.net/embed/b712584d5def413aa86cbdcfa8c222dd" },
  ],
};